# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/middleman
image: ruby:2.3

variables:
  S3_BUCKET_STAGING: "vision-prodriver/preview"
  S3_BUCKET_PRODUCTION: "vision-prodriver/website"
  CF_DISTRIBUTION_ID: "EPA1ZL5B1HOQW"

stages:
  - build
  - deploy

cache:
  paths:
  - vendor
  - public

build:
  stage: build
  script:
  - rm -Rf public
  - apt-get update -yqqq
  - apt-get install -y nodejs npm
  - bundle install --path vendor && npm install
  - bundle exec middleman build --environment="production" --build-dir=public --clean

staging:
  stage: deploy
  image: python:latest
  script:
  - apt-get update -yqqq
  - pip install awscli
  - aws s3 sync --sse --delete public s3://$S3_BUCKET_STAGING/ --acl public-read
  environment:
    name: staging
  only:
  - develop

production:
  stage: deploy
  image: python:latest
  script:
  - apt-get update -yqqq
  - pip install awscli
  - aws s3 sync --sse --delete public s3://$S3_BUCKET_PRODUCTION/ --acl public-read
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CF_DISTRIBUTION_ID --paths '/*'
  environment:
    name: production
  only:
  - master
  when: manual
